name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Run tests
        run: deno test 
      - name: Lint
        run: deno lint
      - name: Check fmt
        run: deno fmt --check
